#!/usr/bin/env bash

# The official packages repository and community packages repository mirrors are listed at: https://www.deepin.org/en/mirrors/packages/
#https://github.com/mviereck/dockerfile-x11docker-deepin/issues/25#issuecomment-732643390
#https://www.deepin.org/zh/2020/08/06/deepin-system-updates-2020-08-06/
#https://www.deepin.org/en/2020/11/19/statements/
OPENSOURCE_MIRROR=mirrors.tuna.tsinghua.edu.cn
DEEPIN_REPOSITORY=https://$OPENSOURCE_MIRROR/deepin
DEEPIN_PRINTER_REPOSITORY=https://community-packages.deepin.com/printer
# The folloiwng info is obtained from the desktop environment installed using deepin-desktop-community-20.3-amd64.iso
DEEPIN_APPSTORE_REPOSITORY=https://com-store-packages.uniontech.com/appstore

DEEPIN_RELEASE=apricot
DEEPIN_PRINTER_RELEASE=eagle
DEEPIN_APPSTORE_RELEASE=deepin

#https://docs.docker.com/docker-hub/builds/advanced/#environment-variables-for-building-and-testing

#    SOURCE_BRANCH: the name of the branch or the tag that is currently being tested.
#    SOURCE_COMMIT: the SHA1 hash of the commit being tested.
#    COMMIT_MSG: the message from the commit being tested and built.
#    DOCKER_REPO: the name of the Docker repository being built.
#    DOCKERFILE_PATH: the dockerfile currently being built.
#    DOCKER_TAG: the Docker repository tag being built.
#    IMAGE_NAME: the name and tag of the Docker repository being built. (This variable is a combination of DOCKER_REPO:DOCKER_TAG.)

