#!/usr/bin/env bash

script_realpath="$(realpath -e -- "${BASH_SOURCE[0]}")"
script_dirname=$(
cd -P -- "$(dirname -- "${BASH_SOURCE[0]}")" &&
pwd -P
)
script_name=$(basename -- "${BASH_SOURCE[0]}")

pkg_repo=${script_realpath%.*}
script_realdirname=${script_realpath%/*}
script_realname=${script_realpath##*/}
script_realbasename=${script_realname%.*}
script_realextname=${script_realname##*.}

script_path=$script_dirname/$script_name
script_basename=${script_name%.*}
script_extname=${script_name##*.}

#https://docs.docker.com/engine/reference/commandline/build/
#https://docs.docker.com/engine/reference/builder/#env
#https://docs.docker.com/engine/reference/builder/#arg
#https://docs.docker.com/engine/reference/builder/#environment-replacement
#https://peihsinsu.gitbooks.io/docker-note-book/content/dockerfile-env-vs-arg.html

#Check whether the proxies are used with the following commands.
#sudo tcpdump -i any port 8080
#sudo tcpdump -i any port 18889


#https://github.com/andyneff/docker_hook_test
#https://docs.docker.com/docker-hub/builds/advanced/
#https://github.com/docker/hub-feedback/issues/508
#https://github.com/docker/hub-feedback/issues/508#issuecomment-240397523
#https://github.com/docker/hub-feedback/issues/508#issuecomment-240616319
#https://codeclimbing.com/automate-your-builds-on-docker-hub-by-writing-a-build-hook-script/
#https://github.com/SamueleA/docker-hub-auto-build-tutorial
#https://hub.docker.com/repository/docker/samueleago/auto-build-tutorial


#https://docs.docker.com/docker-hub/builds/advanced/#environment-variables-for-building-and-testing

#    SOURCE_BRANCH: the name of the branch or the tag that is currently being tested.
#    SOURCE_COMMIT: the SHA1 hash of the commit being tested.
#    COMMIT_MSG: the message from the commit being tested and built.
#    DOCKER_REPO: the name of the Docker repository being built.
#    DOCKERFILE_PATH: the dockerfile currently being built.
#    DOCKER_TAG: the Docker repository tag being built.
#    IMAGE_NAME: the name and tag of the Docker repository being built. (This variable is a combination of DOCKER_REPO:DOCKER_TAG.)

echo SOURCE_BRANCH=$SOURCE_BRANCH
echo SOURCE_COMMIT=$SOURCE_COMMIT
echo COMMIT_MSG=$COMMIT_MSG
echo DOCKER_REPO=$DOCKER_REPO
echo DOCKERFILE_PATH=$DOCKERFILE_PATH
echo DOCKER_TAG=$DOCKER_TAG
echo IMAGE_NAME=$IMAGE_NAME

. $script_realdirname/environment
echo Some customized variables are shown below:
echo DEEPIN_MIRROR=$DEEPIN_MIRROR
echo DEEPIN_APPSTORE_MIRROR=$DEEPIN_APPSTORE_MIRROR
echo DEEPIN_RELEASE=${DEEPIN_RELEASE}
echo newTAGS=${newTAGS}


docker build --build-arg DEEPIN_MIRROR=${DEEPIN_MIRROR} \
             --build-arg DEEPIN_APPSTORE_MIRROR=${DEEPIN_APPSTORE_MIRROR} \
             --build-arg DEEPIN_RELEASE=${DEEPIN_RELEASE} \
             -t ${IMAGE_NAME} .


